name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/airflow:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/airflow:${{ github.sha }}

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/airflow:${{ github.sha }}

    - name: Test Airflow DAGs
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/airflow:${{ github.sha }} airflow dags list
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/airflow:${{ github.sha }} airflow dags test example_dag 2023-01-01

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying Docker image to production..."
        # Add your deployment steps here

