name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Initialize Airflow database
      run: |
        export AIRFLOW_HOME=$(pwd)/airflow
        airflow db init

    - name: Run tests
      run: |
        export AIRFLOW_HOME=$(pwd)/airflow
        python -m unittest discover

    - name: Build Docker image
      run: docker build -t your-docker-image-name .

    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker push your-docker-image-name
